### ISSUE TITLE
Custom output stream

### ISSUE THREAD

**Issue by alii** [cnrad/iridi#1]
be able to return the value or send it to a custom output stream

**Comment by hexiro** [comment]
@cnrad maybe this one can be `iridi.beautify` and then to print it it will be `iridi.print`?

**Comment by alii** [comment]
no shut up hexiro

**Comment by alii** [comment]
soryy for my previous comment

**Comment by punctuations** [comment]
> be able to return the value or send it to a custom output stream

what he said
